### ISSUE TITLE
Replace HTTP client implementation

### ISSUE THREAD

**Issue by joshgav** [MSOpenTech/orc-for-android#3]
The [AndroidHttpClient](http://developer.android.com/reference/android/net/http/AndroidHttpClient.html) has now been deprecated. Refactor our HTTP client implementation to use [URLConnection](http://developer.android.com/reference/java/net/URLConnection.html) and friends.

**Comment by marcote** [comment]
Add a new Resolver using okio library : 618c4ebcb2d352f944a586faf2a1593fa043a0c0
